### ISSUE TITLE
Error in Matplotlib in TADtool

### ISSUE THREAD

**Issue by LeonardoLed** [vaquerizaslab/tadtool#11]
Hi there, I executed TADtool in MAC OS and it showed this message:  

```
C02ST7LHFVH4:tadtool-master andoku01$ tadtool plot examples/chr12_20-35Mb.matrix.txt examples/chr12_20-35Mb_regions.bed chr12:31000000-33000000
2017-11-21 09:35:52,307 INFO Loading regions...
2017-11-21 09:35:52,311 INFO Checking plotting region in matrix...
2017-11-21 09:35:52,311 INFO Loading matrix...
2017-11-21 09:35:52,729 INFO Getting window sizes...
2017-11-21 09:35:52,729 INFO Calculating index...
100% (100 of 100) |###########################################################################################################################| Elapsed Time: 0:00:10 Time: 0:00:10
2017-11-21 09:36:03,380 INFO Done. Showing plot...
Traceback (most recent call last):
  File "/usr/local/bin/tadtool", line 4, in <module>
    __import__('pkg_resources').run_script('tadtool==0.75', 'tadtool')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1674, in run_script
    exec(script_code, namespace, namespace)
  File "/Library/Python/2.7/site-packages/tadtool-0.75-py2.7.egg/EGG-INFO/scripts/tadtool", line 405, in <module>
    
  File "/Library/Python/2.7/site-packages/tadtool-0.75-py2.7.egg/EGG-INFO/scripts/tadtool", line 41, in __init__
    
  File "/Library/Python/2.7/site-packages/tadtool-0.75-py2.7.egg/EGG-INFO/scripts/tadtool", line 204, in plot
    
  File "build/bdist.macosx-10.12-intel/egg/tadtool/plot.py", line 675, in plot
  File "build/bdist.macosx-10.12-intel/egg/tadtool/plot.py", line 202, in plot
  File "build/bdist.macosx-10.12-intel/egg/tadtool/plot.py", line 356, in _plot
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/axes.py", line 7755, in pcolormesh
    collection.set_cmap(cmap)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/cm.py", line 305, in set_cmap
    cmap = get_cmap(cmap)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/cm.py", line 161, in get_cmap
    raise ValueError("Colormap %s is not recognized" % name)
ValueError: Colormap plasma is not recognized
```

how can I solve this problem?

Thanks

**Comment by vaquerizaslab-old** [comment]
Looks like your `matplotlib` version is either outdated or does not yet supply the latest colormaps. You can try uninstalling and reinstalling matplotlib like this:

```
pip uninstall matplotlib
pip install matplotlib
```

(might require `sudo` or alternatively use the `--user` parameter). Instead, you can also try upgrading your existing installation:

```
pip install --upgrade matplotlib
```

**Comment by LeonardoLed** [comment]
Thanks a lot
