### ISSUE TITLE
Error in plot

### ISSUE THREAD

**Issue by RuiqinZheng** [vaquerizaslab/tadtool#12]
tadtool plot ../hicpro2juicer/juicer_matrix_to_hicpro_matrix/square_matrix/2X_50kb_chr1.sqm.matrix ../tad/chr1_50kb.bed chr1:100000-300000
2017-12-05 22:12:35,831 INFO Loading regions...
2017-12-05 22:12:35,865 INFO Checking plotting region in matrix...
2017-12-05 22:12:35,865 INFO Loading matrix...
Hello,Thanks for your software.
but I meet some problem. here I list the error messages, so how can I do?

2017-12-05 22:12:36,372 INFO Getting window sizes...
2017-12-05 22:12:36,373 INFO Calculating index...
100% (100 of 100) |###########################################################################| Elapsed Time: 0:00:12 Time: 0:00:12
2017-12-05 22:14:30,739 INFO Done. Showing plot...
Traceback (most recent call last):
  File "/public/home/rqzheng/anaconda2/bin/tadtool", line 405, in <module>
    TADtool()
  File "/public/home/rqzheng/anaconda2/bin/tadtool", line 41, in __init__
    getattr(self, args.command)()
  File "/public/home/rqzheng/anaconda2/bin/tadtool", line 204, in plot
    fig, axes = tad_plot.plot(plotting_region)
  File "/public/home/rqzheng/anaconda2/lib/python2.7/site-packages/tadtool/plot.py", line 607, in plot
    self.fig = plt.figure(figsize=(10, 10))
  File "/public/home/rqzheng/anaconda2/lib/python2.7/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/public/home/rqzheng/anaconda2/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/public/home/rqzheng/anaconda2/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/public/home/rqzheng/anaconda2/lib/python2.7/lib-tk/Tkinter.py", line 1820, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

Best wishes

**Comment by vaquerizaslab-old** [comment]
Please see our answer to issue #2, it appears to be the same problem.
