### ISSUE TITLE
python functionality broken

### ISSUE THREAD

**Issue by benayang** [vaquerizaslab/tadtool#27]
Hello,

It looks like the python implementation of tadtool consistently runs into the following error when calling TADs or insulation scores. Is there a way to correct this?

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/benyang/miniconda3/envs/HIC/lib/python3.7/site-packages/tadtool/tad.py", line 543, in insulation_index
    bin_size = regions[0].end-regions[0].start+1
AttributeError: 'list' object has no attribute 'end'

Thanks,
Ben

**Comment by kaukrise** [comment]
Hi, can you please run `tadtool` with the example files provided in the `examples` folder here on GitHub to see if the error persists there?

```
tadtool plot examples/chr12_20-35Mb.matrix.txt examples/chr12_20-35Mb_regions.bed chr12:31000000-33000000
```

If so, can you please post the complete `tadtool` logging output, so I can review where exactly it gets stuck? Thanks!

I tried running the sample data from a fresh Python 3.7 virtual environment on my system and could not reproduce the issue.

**Comment by benayang** [comment]
The command line implementation works well, so no issues there! I'm running into issues trying to run tadtool as a python script. The error is shown below. 

```
Hi-C/04_FANC/tadtool via 🐍 v3.7.3 via 📐 v3.4.4 via 🅒  HIC took 1m54s
✦11 ❯ python3
Python 3.7.3 | packaged by conda-forge | (default, Dec  6 2019, 08:54:18)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tadtool.tad as tad
>>> import tadtool.plot as tp
>>> matrix = tad.load_matrix("./tadtool/examples/chr12_20-35Mb.matrix.txt")
>>> regions = tad.load_regions("./tadtool/examples/chr12_20-35Mb_regions.bed")
>>> tad_plot = tp.TADtoolPlot(matrix, regions, norm='lin', max_dist=1000000, algorithm='insulation')
N/A% (0 of 100) |                                                                                                            | Elapsed Time: 0:00:00 ETA:  --:--:--Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/benyang/miniconda3/envs/HIC/lib/python3.7/site-packages/tadtool/plot.py", line 547, in __init__
    tad_method=self.tad_algorithm, window_sizes=window_sizes)
  File "/home/benyang/miniconda3/envs/HIC/lib/python3.7/site-packages/tadtool/tad.py", line 679, in data_array
    da.append(tad_method(hic_matrix, regions, window_size, **kwargs))
  File "/home/benyang/miniconda3/envs/HIC/lib/python3.7/site-packages/tadtool/tad.py", line 543, in insulation_index
    bin_size = regions[0].end-regions[0].start+1
AttributeError: 'list' object has no attribute 'end'
```

**Comment by kaukrise** [comment]
Hey, try this:

```python
import tadtool.tad as tad
import tadtool.plot as tp
import matplotlib.pyplot as plt

matrix = tad.load_matrix("/Users/kkruse/dev/tadtool/examples/chr12_20-35Mb.matrix.txt")
regions, _ = tad.load_regions("/Users/kkruse/dev/tadtool/examples/chr12_20-35Mb_regions.bed")

tad_plot = tp.TADtoolPlot(matrix, regions, norm='lin', max_dist=1000000, algorithm='insulation')
tad_plot.plot('chr12:31000000-34000000')
plt.show()
```

`load_regions` returns a tuple, only the first element is the regions list.

**Comment by benayang** [comment]
Thanks, this works!
